const enum QUERY_KEY {
  LOGIN = 'LOGIN',
  RAID_LIST = 'RAID_LIST',
  ACCOUNT_RAID_LIST = 'ACCOUNT_RAID_LIST',
  ORGANIZATION_LIST = 'ORGANIZATION_LIST',
  CHARACTER_LIST = 'CHARACTER_LIST',
  TODO_LIST = "TODO_LIST",
  ACCOUNT_TODO_LIST = "ACCOUNT_TODO_LIST",
  RESERVATION_LIST = 'RESERVATION_LIST'
}

export default QUERY_KEY;