const enum RECOIL_KEY {
  MODAL_CONTROLLER = 'MODAL_CONTROLLER',
  LOGIN = 'LOGIN',
  USER_REFRESH = 'USER_REFRESH',
  RESERVATION = 'RESERVATION',
  RESERVATION_DATE = 'RESERVATION_DATE',
  RESERVATION_RAID_TYPE = 'RESERVATION_RAID_TYPE',
}

export default RECOIL_KEY;
